name: Checks

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint

  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run check

  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Generating candids
        run: npm run generate
      - name: Check if dirty
        run: if [[ -n $(git status --porcelain) ]]; then exit 1; fi

  may-merge:
    needs: ['check', 'lint', 'generate']
    runs-on: ubuntu-latest
    steps:
      - name: Cleared for merging
        run: echo OK
